stages:
  - test
  - deploy

ubuntu18-test:
  stage: test
  image: ilrocstar/calculix-test-ubuntu18:v1
  script:
    - mkdir build
    - cd build
    - >
      cmake ..
      -DCMAKE_INSTALL_PREFIX=../install
      -DCMAKE_BUILD_TYPE=Release
      -DBUILD_SHARED_LIBS=ON
      -DENABLE_TESTING=ON
      -DENABLE_PAR=ON
      -DENABLE_CSC=ON
      -DENABLE_CFD_SUPPORT=ON
      -DMPI_CXX_COMPILER=/usr/bin/mpicxx.openmpi
      -DMPIEXEC_EXECUTABLE=/usr/bin/mpiexec.openmpi
    - make -j$(nproc)
    - make install
    - ctest --output-on-failure
    - cpack -G DEB
  artifacts:
    paths:
      - "build/*.deb"

centos7-test:
  stage: test
  image: ilrocstar/calculix-test-centos7:v1
  script:
    - mkdir build
    - cd build
    - >
      cmake3 ..
      -DCMAKE_INSTALL_PREFIX=../install
      -DCMAKE_BUILD_TYPE=Release
      -DBUILD_SHARED_LIBS=ON
      -DENABLE_TESTING=ON
      -DENABLE_PAR=ON
      -DENABLE_CSC=ON
      -DENABLE_CFD_SUPPORT=ON
      -DMPI_CXX_COMPILER=/usr/lib64/openmpi/bin/mpicxx
      -DMPIEXEC_EXECUTABLE=/usr/lib64/openmpi/bin/mpiexec
      -DBOOST_INCLUDEDIR=/usr/include/boost169
      -DBOOST_LIBRARYDIR=/usr/lib64/boost169
    - make -j$(nproc)
    - make install
    - ctest3 --output-on-failure
    - cpack3 -G RPM
  artifacts:
    paths:
      - "build/*.rpm"

deploy-all:
  stage: deploy
  only:
    - master@rocstar_modern/calculix-csc
  script:
    - apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - scp -r build/*.deb nemosys@192.168.1.122:/home/nemosys/repo
    - scp -r build/*.rpm nemosys@192.168.1.122:/home/nemosys/rpmrepo
  dependencies:
    - ubuntu18-test
    - centos7-test